const seed={schedule:[{id:1,date:"1/10",time:"09:30",title:"抵達熊本機場",location:"熊本機場",note:"領取行李後搭巴士進市區"},{id:2,date:"1/11",time:"10:00",title:"熊本城散步",location:"熊本城",note:"記得帶護照，現場購票"}],packing:[{id:1,name:"護照",category:"重要",done:true},{id:2,name:"行動電源",category:"電子",done:false},{id:3,name:"保暖外套",category:"衣物",done:false}],transport:[{id:1,type:"航班",code:"CI194",from:"桃園 T2",to:"熊本 KMJ",date:"2027-01-10",time:"06:50",note:"起飛前 2.5 小時集合"}],expenses:[{id:1,title:"機場巴士",amount:1200,currency:"JPY",payer:"阿偉",category:"交通"}]};
let data=JSON.parse(localStorage.getItem('tripMateData')||'null')||seed;let packFilter='全部';const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];const save=()=>{localStorage.setItem('tripMateData',JSON.stringify(data));render();if(TRIP_CONFIG.API_URL)fetch(TRIP_CONFIG.API_URL,{method:'POST',body:JSON.stringify({action:'save',data})}).catch(()=>toast('已存於本機，雲端同步失敗'));};const toast=t=>{const x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1800)};
function formatDateValue(value){if(!value)return '';if(value instanceof Date&&!Number.isNaN(value.getTime()))return `${value.getFullYear()}-${value.getMonth()+1}-${value.getDate()}`;const text=String(value);const plain=text.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);if(plain)return `${plain[1]}-${Number(plain[2])}-${Number(plain[3])}`;if(!text.includes('T'))return text;const date=new Date(text);return Number.isNaN(date.getTime())?text:`${date.getFullYear()}-${date.getMonth()+1}-${date.getDate()}`;}
function formatTimeValue(value){if(!value)return '';if(value instanceof Date&&!Number.isNaN(value.getTime()))return `${String(value.getHours()).padStart(2,'0')}:${String(value.getMinutes()).padStart(2,'0')}`;const text=String(value);const short=text.match(/^(\d{1,2}):(\d{2})/);if(short)return `${String(Number(short[1])).padStart(2,'0')}:${short[2]}`;if(!text.includes('T'))return text;const date=new Date(text);return Number.isNaN(date.getTime())?text:`${String(date.getHours()).padStart(2,'0')}:${String(date.getMinutes()).padStart(2,'0')}`;}
function dateInputValue(value){const text=String(value||'');const plain=text.match(/^(\d{4})-(\d{1,2})-(\d{1,2})$/);if(plain)return `${plain[1]}-${String(plain[2]).padStart(2,'0')}-${String(plain[3]).padStart(2,'0')}`;if(!text.includes('T'))return '';const date=new Date(text);return Number.isNaN(date.getTime())?'':`${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
function timeInputValue(value){return formatTimeValue(value);}
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active')});
function render(){const done=data.packing.filter(x=>x.done).length;$('#packingProgress').textContent=data.packing.length?Math.round(done/data.packing.length*100)+'%':'0%';$('#totalExpense').textContent='¥'+data.expenses.filter(x=>x.currency==='JPY').reduce((a,b)=>a+Number(b.amount),0).toLocaleString();const days=Math.ceil((new Date(TRIP_CONFIG.TRIP_START)-new Date())/864e5);$('#countdown').textContent=days>0?days+' 天':days===0?'今天':'旅途中';
$('#scheduleList').innerHTML=data.schedule.map(x=>`<article class="item"><div class="day">${esc(formatDateValue(x.date))}<div class="meta">${esc(formatTimeValue(x.time))}</div></div><div><h3>${esc(x.title)}</h3><div class="meta">📍 ${esc(x.location||'未填位置')}</div><div class="meta">${esc(x.note||'')}</div></div><button class="edit" onclick="openEditor('schedule',${x.id})">編輯</button></article>`).join('')||empty('還沒有行程');
const cats=['全部',...new Set(data.packing.map(x=>x.category))];$('#packingFilters').innerHTML=cats.map(c=>`<button class="${c===packFilter?'active':''}" onclick="packFilter='${c}';render()">${c}</button>`).join('');$('#packingList').innerHTML=data.packing.filter(x=>packFilter==='全部'||x.category===packFilter).map(x=>`<div class="packing-row ${x.done?'done':''}"><input type="checkbox" ${x.done?'checked':''} onchange="togglePack(${x.id})"><span>${esc(x.name)}</span>${x.member?`<span class="pill">${esc(x.member)}</span>`:''}<span class="pill">${esc(x.category)}</span><button class="edit" onclick="openEditor('packing',${x.id})">編輯</button></div>`).join('')||empty('這個分類還沒有物品');
$('#transportList').innerHTML=data.transport.map(x=>`<article class="transport"><div class="meta">${esc(x.type)} · ${esc(x.code)}</div><div class="route"><span>${esc(x.from)}</span><i class="line"></i><span>${esc(x.to)}</span></div><div>${esc(formatDateValue(x.date))}　${esc(formatTimeValue(x.time))}</div><div class="meta">${esc(x.note||'')}</div><button class="edit" onclick="openEditor('transport',${x.id})">編輯</button></article>`).join('')||empty('還沒有交通資訊');
const total=data.expenses.reduce((a,b)=>a+Number(b.amount),0);$('#expenseSummary').innerHTML=`<div class="summary"><div>目前共支出</div><strong>¥${total.toLocaleString()}</strong><div>${data.expenses.length} 筆共同費用</div></div>`;$('#expenseList').innerHTML=data.expenses.map(x=>`<div class="expense-row"><div><strong>${esc(x.title)}</strong><div class="meta">${esc(x.payer)} 付款 · ${esc(x.category)}</div></div><strong>${x.currency==='JPY'?'¥':x.currency+' '}${Number(x.amount).toLocaleString()}</strong><button class="edit" onclick="openEditor('expense',${x.id})">編輯</button></div>`).join('')||empty('還沒有支出');}
const schemas={schedule:[['date','日期','text'],['time','時間','time'],['title','主要事項','text'],['location','位置','text'],['note','備註','textarea']],packing:[['name','物品名稱','text'],['member','團員姓名','text'],['category','分類','text']],transport:[['type','類型','select','航班,高鐵,火車,巴士,租車'],['code','班次／航班編號','text'],['from','出發地','text'],['to','目的地','text'],['date','日期','date'],['time','時間','time'],['note','備註','textarea']],expense:[['title','項目','text'],['amount','金額','number'],['currency','幣別','select','JPY,TWD'],['payer','付款人','text'],['category','分類','select','餐飲,交通,住宿,門票,購物,其他']]};
function openEditor(type,id){const key=type==='expense'?'expenses':type;const obj=id?data[key].find(x=>x.id===id):{};$('#modalTitle').textContent=(id?'編輯':'新增')+({schedule:'行程',packing:'物品',transport:'交通',expense:'支出'}[type]);$('#formFields').innerHTML=schemas[type].map(([n,l,t,o])=>`<div class="field"><label>${l}</label>${t==='textarea'?`<textarea name="${n}">${esc(obj[n]||'')}</textarea>`:t==='select'?`<select name="${n}">${o.split(',').map(v=>`<option ${obj[n]===v?'selected':''}>${v}</option>`).join('')}</select>`:`<input name="${n}" type="${t}" value="${esc(n==='date'?(t==='date'?dateInputValue(obj[n]):formatDateValue(obj[n])):n==='time'?timeInputValue(obj[n]):obj[n]||'')}">`}</div>`).join('');$('#saveBtn').onclick=e=>{e.preventDefault();const values=Object.fromEntries(new FormData($('#editor form')));if(id)Object.assign(obj,values);else data[key].push({id:Date.now(),...values,done:false});save();$('#editor').close();toast('已儲存')};$('#editor').showModal()}
function togglePack(id){const x=data.packing.find(x=>x.id===id);x.done=!x.done;save()}function empty(t){return `<div class="item meta">${t}</div>`}function esc(v){return String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}$$('[data-add]').forEach(b=>b.onclick=()=>openEditor(b.dataset.add));$('#syncBtn').onclick=async()=>{if(!TRIP_CONFIG.API_URL)return toast('目前使用此裝置儲存');try{const r=await fetch(TRIP_CONFIG.API_URL+'?action=read');data=await r.json();save();toast('同步完成')}catch(e){toast('同步失敗，請檢查設定')}};render();
